name: build

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Create test env
        run: cp .env.example .env

      - name: Create gateways config
        run: cp gateways.yml.example gateways.yml

      - name: Create network
        run: docker network create finteh-network

      - name: Run postgres container
        run: docker-compose run -d postgres

      - name: Build database container
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose exec -T booker pipenv run pytest
